package trainning.broad.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * COMMENT モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Comment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Integer commentId;

	private String content;

	private Date createAt;

	private Date updateAt;

	private Post post;
	private User user;

	public Comment() {
		post = new Post();
		user = new User();
	}

	public Integer getCommentId() {
		return commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateAt() {
		return createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	public Date getUpdateAt() {
		return updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
