package trainning.broad.bean;

import java.io.Serializable;

/**
 * POST_TAG モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class PostTag implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Integer postTagId;

	private Post post;

	private Tag tag;

	public PostTag() {
		post = new Post();
		tag = new Tag();
	}

	public Integer getPostTagId() {
		return postTagId;
	}

	public void setPostTagId(Integer postTagId) {
		this.postTagId = postTagId;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public Tag getTag() {
		return tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
