package trainning.broad.bean;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * POST モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Post implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Integer postId;

	private String postName;

	private String content;

	private Timestamp createAt;

	private Timestamp updateAt;

	private User user;
	public Post() {
		this.user = new User();
	}

	public Integer getPostId() {
		return postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	public String getPostName() {
		return postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Timestamp getCreateAt() {
		return createAt;
	}

	public void setCreateAt(Timestamp createAt) {
		this.createAt = createAt;
	}

	public Timestamp getUpdateAt() {
		return updateAt;
	}

	public void setUpdateAt(Timestamp updateAt) {
		this.updateAt = updateAt;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
