package trainning.broad.bean;

import java.io.Serializable;

/**
 * POST_TAG モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class PostTag implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Integer postTagId;

	private Integer postId;

	private Integer tagId;

	public PostTag() {
	}

	public Integer getPostTagId() {
		return postTagId;
	}

	public void setPostTagId(Integer postTagId) {
		this.postTagId = postTagId;
	}

	public Integer getPostId() {
		return postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	public Integer getTagId() {
		return tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}
}

