package trainning.broad.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * POST モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Post implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** post_id. */
	private Integer postId;

	/** post_name. */
	private String postName;

	/** content. */
	private String content;

	/** user_id. */
	private Integer userId;

	/** create_at. */
	private Date createAt;

	/** update_at. */
	private Date updateAt;

	/**
	 * コンストラクタ.
	 */
	public Post() {
	}

	/**
	 * post_id を設定します.
	 *
	 * @param postId
	 *            post_id
	 */
	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	/**
	 * post_id を取得します.
	 *
	 * @return post_id
	 */
	public Integer getPostId() {
		return this.postId;
	}

	/**
	 * post_name を設定します.
	 *
	 * @param postName
	 *            post_name
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * post_name を取得します.
	 *
	 * @return post_name
	 */
	public String getPostName() {
		return this.postName;
	}

	/**
	 * content を設定します.
	 *
	 * @param content
	 *            content
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * content を取得します.
	 *
	 * @return content
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * user_id を設定します.
	 *
	 * @param userId
	 *            user_id
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * user_id を取得します.
	 *
	 * @return user_id
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * create_at を設定します.
	 *
	 * @param createAt
	 *            create_at
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * create_at を取得します.
	 *
	 * @return create_at
	 */
	public Date getCreateAt() {
		return this.createAt;
	}

	/**
	 * update_at を設定します.
	 *
	 * @param updateAt
	 *            update_at
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * update_at を取得します.
	 *
	 * @return update_at
	 */
	public Date getUpdateAt() {
		return this.updateAt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((postId == null) ? 0 : postId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Post other = (Post) obj;
		if (postId == null) {
			if (other.postId != null) {
				return false;
			}
		} else if (!postId.equals(other.postId)) {
			return false;
		}
		return true;
	}

}
