package trainning.broad.bean;

import java.io.Serializable;

/**
 * TAG モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tag implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private Integer tagId;

	private String tagName;

	public Tag() {
	}

	public Integer getTagId() {
		return tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}
}

